### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by Kevin412-shanzi** [ssttkkl/nonebot-plugin-pixivbot#108]
内部错误：<class 'pixivpy_async.error.NoTokenError'>No access_token Found!
怎么解决啊

**Comment by ssttkkl** [comment]
无法获取access_token的问题，检查网络或代理设置

**Comment by Kevin412-shanzi** [comment]
pydantic.error_wrappers.ValidationError: 1 validation error for Config
pixiv_block_tags
  value is not a valid list (type=type_error.list)
我改了指定过滤词条又出现了新的报错。
我是这么填的
pixiv_block_tags=[R-18]

**Comment by ssttkkl** [comment]
```
pixiv_block_tags=["R-18"]
```
需要按照JSON文本的格式

**Comment by Kevin412-shanzi** [comment]
谢谢大佬，我已经在爱发电支持您！
pixivpy_async.error.TokenError: Get access_token error!
Response: None
Error: {'has_error': True, 'errors': {'system': {'message': 'Invalid refresh token', 'code': 1508}}, 'error': 'invalid_grant'}
我现在在海外服务器上运行着，没有配代理，刚才一直好好的，现在又开始报错这个了，会是什么原因呢

**Comment by Kevin412-shanzi** [comment]
好的我已经解决了

**Comment by ssttkkl** [comment]
感谢支持！

**Comment by ssttkkl** [comment]
> Error: {'has_error': True, 'errors': {'system': {'message': 'Invalid refresh token', 'code': 1508}}, 'error': 'invalid_grant'}

这里说refresh_token无效，我也没遇到过一会可以用一会又不行的情况

**Comment by HL-Light** [comment]
![5(S`IKM YCA(R(%~~UM@()9](https://user-images.githubusercontent.com/116658416/209335749-c81f944c-6894-4ff6-9a22-7398f94dd343.jpg)
是这样填吗

**Comment by ssttkkl** [comment]
是
