### ISSUE TITLE
希望增加对r18的筛选功能（黑白名单）

### ISSUE THREAD

**Issue by HL-Light** [ssttkkl/nonebot-plugin-pixivbot#109]
群内有时候不方便，希望有类似黑白名单的r18筛选功能

**Comment by ssttkkl** [comment]
不知道你说的黑白名单是怎么样的

如果你指的是对所有用户过滤R18，一种实现方法是在pixiv_block_tags里加上R-18，另一种更保险的方法是把账号的R18开关关了

如果你指的是群聊过滤R18、私聊无限制，这与插件目前的设计是冲突的，因为插件除了QQ外还能在其他平台使用

如果你指的是只对特定用户开放R18，可以计划通过[nonebot-plugin-access-control](https://github.com/ssttkkl/nonebot-plugin-access-control)来实现

**Comment by ssttkkl** [comment]
只对特定用户开放R18，以及通过[nonebot-plugin-access-control](https://github.com/ssttkkl/nonebot-plugin-access-control)来实现

**Comment by HL-Light** [comment]
我的黑白名单的意思是，比如设置全局r-18屏蔽，通过但白名单（配置文件列表设置之类的）来放过屏蔽，黑名单相反

**Comment by ssttkkl** [comment]
全局禁用R18
```
/ac subject all deny service nonebot_plugin_pixivbot.r18
```

对特定用户开启R18（注意群聊也会受到影响）
```
/ac subject onebot:12345678 allow service nonebot_plugin_pixivbot.r18
```

对特定群组开启R18
```
/ac subject onebot:g87654321 allow service nonebot_plugin_pixivbot.r18
```
