### ISSUE TITLE
关于命令unwatch语句的使用

### ISSUE THREAD

**Issue by ANGJustinl** [ssttkkl/nonebot-plugin-pixivbot#112]
![81U%U5L _O}(SP@EC$%J6(S](https://user-images.githubusercontent.com/96008766/209486300-eb0e0a59-ddcd-4093-8a82-40b1da7a5987.png)
这个没法unwatch啊，我按照文档内方法怎么试都没法解除

**Comment by ANGJustinl** [comment]
![image](https://user-images.githubusercontent.com/96008766/209486507-fd205fa5-9d17-48ad-b131-2980165b6602.png)

![%45 LYLL83{P~G(OXYLDL~E](https://user-images.githubusercontent.com/96008766/209486519-9bcbf575-c21d-4873-a5c6-5d8c5ca3596f.png)
大寄

**Comment by ssttkkl** [comment]
方括号内的是id
________________________________

**Comment by ANGJustinl** [comment]
好的太感谢了！
