### ISSUE TITLE
希望能应对某种程度的TIMEOUT错误提供后台重试

### ISSUE THREAD

**Issue by Ctumille** [ssttkkl/nonebot-plugin-pixivbot#119]
01-06 18:43:56 [SUCCESS] nonebot | OneBot V11 3429318375 | [message.group.normal]: Message -1637898823 from 415662910@[群:783759481] "来张图"
01-06 18:43:56 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_pixivbot.handler.common.random_recommended_illust)
01-06 18:43:56 [INFO] nonebot_plugin_pixivbot | [mediator] recommended_illusts cache_strategy=NORMAL
01-06 18:43:56 [INFO] nonebot_plugin_pixivbot | [pixiv_service] choice [98288870]
01-06 18:43:56 [INFO] nonebot_plugin_pixivbot | [mediator] image 98288870 cache_strategy=NORMAL
01-06 18:43:56 [INFO] nonebot_plugin_pixivbot | [local] image 98288870
01-06 18:43:56 [INFO] nonebot_plugin_pixivbot | [mediator] no cache or cache expired
01-06 18:43:56 [INFO] nonebot_plugin_pixivbot | [remote] image 98288870
01-06 18:44:06 [ERROR] nonebot_plugin_pixivbot | error <class 'asyncio.exceptions.TimeoutError'> raised by agen (IMAGE illust_id=98288870)

如题，经常会出现如上错误，不清楚是哪一部分出了问题但是总之它经常这样然后报“网络错误”，代理应当是正常运作的因为还是经常能发出来的，但是出现以上错误就比较尴尬

**Comment by ssttkkl** [comment]
1.7.2版本添加了网络错误时自动重试功能
