### ISSUE TITLE
安装插件时报错error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by AyasakiAtre** [ssttkkl/nonebot-plugin-pixivbot#120]
Preparing metadata (setup.py) ... done
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/be/54/5468f25bcadc6877de0bfd253f27e3ce489c3d4489c928cdb38b31ed47cb/greenlet-0.3.1.tar.gz (39 kB)
  Preparing metadata (setup.py) ... done
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/9f/29/c8d0b051afacd0108c26a89824a13fa041299b61e8d9e50a6a35e25c4ec1/greenlet-0.3.tar.gz (37 kB)
  Preparing metadata (setup.py) ... done
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/72/db/0d1a944ba1517256e8b1a080a90297569d8662442631a6b05f8a1c584556/greenlet-0.2.tar.gz (22 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Rin\AppData\Local\Temp\pip-install-eby1tclc\greenlet_a0051fbe720c459da3277333517494c5\setup.py", line 3, in <module>
          import ez_setup
        File "C:\Users\Rin\AppData\Local\Temp\pip-install-eby1tclc\greenlet_a0051fbe720c459da3277333517494c5\ez_setup\__init__.py", line 98
          except pkg_resources.VersionConflict, e:
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      SyntaxError: multiple exception types must be parenthesized
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

环境：win
python3.10.8

**Comment by z316174018** [comment]
我也是，同问

**Comment by ssttkkl** [comment]
目前可以确定是pip依赖解决器的bug导致的，用poetry是没有问题的
一个临时的解决方法是先安装nonebot-plugin-access-control再安装nonebot-plugin-pixivbot

**Comment by AyasakiAtre** [comment]
> 目前可以确定是pip依赖解决器的bug导致的，用poetry是没有问题的 一个临时的解决方法是先安装nonebot-plugin-access-control再安装nonebot-plugin-pixivbot

非常感谢，用这方法成功安装上插件
