### ISSUE TITLE
使用功能时ConnectionResetError

### ISSUE THREAD

**Issue by AyasakiAtre** [ssttkkl/nonebot-plugin-pixivbot#122]
01-13 00:53:25 [SUCCESS] nonebot | OneBot V11 3276928870 | [message.group.normal]: Message 275508025 from xx@[群:xx] "看看图 233"
01-13 00:53:25 [ERROR] nonebot_plugin_pixivbot | error <class 'ConnectionResetError'> raised by agen (IMAGE illust_id=233, page=0)
01-13 00:53:25 [WARNING] nonebot_plugin_pixivbot | ConnectionResetError

![I@YAF805H9N$QNYCLR4CYLN](https://user-images.githubusercontent.com/83602783/212130445-e762c2d3-b3f3-4759-af67-7423e2e7b827.png)

**Comment by AyasakiAtre** [comment]
![image](https://user-images.githubusercontent.com/83602783/212130801-4d7aa946-99f7-4d49-a769-60b43951ceb7.png

弄了几小时实在不行了，求指导

**Comment by ssttkkl** [comment]
顾名思义就是ConnectionResetError（）
要么检查下网络，要么可能是你梯子抽风了过一会再试试
