### ISSUE TITLE
发送来张私家车概率性出问题

### ISSUE THREAD

**Issue by Kimaru-bili** [ssttkkl/nonebot-plugin-pixivbot#125]
日志
![image](https://user-images.githubusercontent.com/40233772/213867859-8cac4d66-e40e-45df-a693-0898ce00d424.png)

**Comment by ssttkkl** [comment]
traceback也截一下完整的
________________________________
From: Kimaru-bili ***@***.***>
Sent: Saturday, January 21, 2023 8:58:48 PM
To: ssttkkl/nonebot-plugin-pixivbot ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ssttkkl/nonebot-plugin-pixivbot] 发送来张私家车概率性出问题 (Issue #125)


日志
[image]<https://user-images.githubusercontent.com/40233772/213867859-8cac4d66-e40e-45df-a693-0898ce00d424.png>

―

**Comment by Kimaru-bili** [comment]
emmm不好意思，重启机器人了(然后就没复现了😢 还改了查询超时时间 好像是查询超时后才会出的问题

**Comment by Kimaru-bili** [comment]
复现了 好像不止私家车 这次事发别的出问题了
01-22 11:02:46 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_pixivbot.handler.common.random_illust) failed.
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 4
               │     └ 7
               └ <function _main at 0xffffa3f79900>
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 4
           │    └ <function BaseProcess._bootstrap at 0xffffa40f4a60>
           └ <SpawnProcess name='SpawnProcess-1' parent=450 started>
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0xffffa40f40d0>
    └ <SpawnProcess name='SpawnProcess-1' parent=450 started>
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'config': <uvicorn.config.Config object at 0xffffa3f8dc00>, 'target': <bound method Server.run of <uvicorn.server.Server obj...
    │    │        │    │        └ <SpawnProcess name='SpawnProcess-1' parent=450 started>
    │    │        │    └ ()
    │    │        └ <SpawnProcess name='SpawnProcess-1' parent=450 started>
    │    └ <function subprocess_started at 0xffffa28d8dc0>
    └ <SpawnProcess name='SpawnProcess-1' parent=450 started>
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
    │              └ [<socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('172.17.0.2', 54672)>]
    └ <bound method Server.run of <uvicorn.server.Server object at 0xffff8ec855d0>>
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ [<socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('172.17.0.2', 54672)>]
           │       │   │    └ <function Server.serve at 0xffffa28d81f0>
           │       │   └ <uvicorn.server.Server object at 0xffff8ec855d0>
           │       └ <function run at 0xffffa3b70af0>
           └ <module 'asyncio' from '/usr/lib/python3.10/asyncio/__init__.py'>
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0xffff82aecdd0>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/dist-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _command at 0xffffa31dfc70>: <Task finished name='Task-624177' coro=<_command() done, defined at /usr/local/lib/py...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0xffff4ffb2680>
          │            │        │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None, 'command_start': None}, '_matched': '来张R18图', '_match...
          │            │        │    └ GroupMessageEvent(time=1674385354, self_id=2858036838, post_type='message', sub_type='normal', user_id=2065820158, message_ty...
          │            │        └ Bot(type='OneBot V11', self_id='2858036838')
          │            └ Matcher(type='message', module=nonebot_plugin_pixivbot.handler.common.random_illust)
          └ <function _run_matcher at 0xffffa2eabc70>
> File "/usr/local/lib/python3.10/dist-packages/nonebot/message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _command at 0xffffa31dfc70>: <Task finished name='Task-624177' coro=<_command() done, defined at /usr/local/lib/py...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0xffff4ffb2680>
          │       │   │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None, 'command_start': None}, '_matched': '来张R18图', '_match...
          │       │   │    └ GroupMessageEvent(time=1674385354, self_id=2858036838, post_type='message', sub_type='normal', user_id=2065820158, message_ty...
          │       │   └ Bot(type='OneBot V11', self_id='2858036838')
          │       └ <function Matcher.run at 0xffffa31df7f0>
          └ Matcher(type='message', module=nonebot_plugin_pixivbot.handler.common.random_illust)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/matcher/matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _command at 0xffffa31dfc70>: <Task finished name='Task-624177' coro=<_command() done, defined at /usr/local/lib/py...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0xffff4ffb2680>
          │    │          │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None, 'command_start': None}, '_matched': '来张R18图', '_match...
          │    │          │    └ GroupMessageEvent(time=1674385354, self_id=2858036838, post_type='message', sub_type='normal', user_id=2065820158, message_ty...
          │    │          └ Bot(type='OneBot V11', self_id='2858036838')
          │    └ <function Matcher.simple_run at 0xffffa31df760>
          └ Matcher(type='message', module=nonebot_plugin_pixivbot.handler.common.random_illust)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/matcher/matcher.py", line 702, in simple_run
    await handler(
          └ Dependent(call=<bound method RandomIllustHandler.on_match of <nonebot_plugin_pixivbot.handler.common.random_illust.RandomIllu...
  File "/usr/local/lib/python3.10/dist-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
                 │    │             │         │    │    │       └ {'bot': Bot(type='OneBot V11', self_id='2858036838'), 'event': GroupMessageEvent(time=1674385354, self_id=2858036838, post_ty...
                 │    │             │         │    │    └ <bound method RandomIllustHandler.on_match of <nonebot_plugin_pixivbot.handler.common.random_illust.RandomIllustHandler objec...
                 │    │             │         │    └ Dependent(call=<bound method RandomIllustHandler.on_match of <nonebot_plugin_pixivbot.handler.common.random_illust.RandomIllu...
                 │    │             │         └ ~R
                 │    │             └ typing.Awaitable
                 │    └ typing.Callable
                 └ <function cast at 0xffffa3c97f40>
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_pixivbot/handler/common/random_illust.py", line 40, in on_match
    await self.handle(word, count=get_count(state), post_dest=post_dest)
          │    │      │           │         │                 └ <nonebot_plugin_pixivbot_onebot_v11.protocol_dep.post_dest.PostDestination object at 0xffff82f2eb00>
          │    │      │           │         └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None, 'command_start': None}, '_matched': '来张R18图', '_match...
          │    │      │           └ <function get_count at 0xffffa23c6440>
          │    │      └ 'R18'
          │    └ <function Handler.handle at 0xffffa23c40d0>
          └ <nonebot_plugin_pixivbot.handler.common.random_illust.RandomIllustHandler object at 0xffff94f7ca00>
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_pixivbot/handler/base.py", line 99, in handle
    await self.interceptor.intercept(self._parse_args_and_actual_handle, *args,
          │    │           │         │    │                               └ ('R18',)
          │    │           │         │    └ <function Handler._parse_args_and_actual_handle at 0xffffa23c41f0>
          │    │           │         └ <nonebot_plugin_pixivbot.handler.common.random_illust.RandomIllustHandler object at 0xffff94f7ca00>
          │    │           └ <function CombinedInterceptor.intercept at 0xffffa23ab250>
          │    └ <nonebot_plugin_pixivbot.handler.interceptor.combined_interceptor.CombinedInterceptor object at 0xffff94f7d030>
          └ <nonebot_plugin_pixivbot.handler.common.random_illust.RandomIllustHandler object at 0xffff94f7ca00>
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_pixivbot/handler/interceptor/combined_interceptor.py", line 45, in intercept
    await self.x.intercept(
          │    │ └ <function CombinedInterceptor.intercept at 0xffffa23ab250>
          │    └ <nonebot_plugin_pixivbot.handler.interceptor.combined_interceptor.CombinedInterceptor object at 0xffff94f7cf70>
          └ <nonebot_plugin_pixivbot.handler.interceptor.combined_interceptor.CombinedInterceptor object at 0xffff94f7d030>
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_pixivbot/handler/interceptor/combined_interceptor.py", line 45, in intercept
    await self.x.intercept(
          │    │ └ <function CombinedInterceptor.intercept at 0xffffa23ab250>
          │    └ <nonebot_plugin_pixivbot.handler.interceptor.combined_interceptor.CombinedInterceptor object at 0xffff94f7cf10>
          └ <nonebot_plugin_pixivbot.handler.interceptor.combined_interceptor.CombinedInterceptor object at 0xffff94f7cf70>
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_pixivbot/handler/interceptor/combined_interceptor.py", line 45, in intercept
    await self.x.intercept(
          │    │ └ <function CombinedInterceptor.intercept at 0xffffa23ab250>
          │    └ <nonebot_plugin_pixivbot.handler.interceptor.combined_interceptor.CombinedInterceptor object at 0xffff94f7ceb0>
          └ <nonebot_plugin_pixivbot.handler.interceptor.combined_interceptor.CombinedInterceptor object at 0xffff94f7cf10>
  [Previous line repeated 3 more times]
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_pixivbot/handler/interceptor/default_error_interceptor.py", line 32, in intercept
    raise e
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_pixivbot/handler/interceptor/default_error_interceptor.py", line 22, in intercept
    await wrapped_func(*args, post_dest=post_dest, silently=silently, **kwargs)
          │             │               │                   │           └ {'count': 1}
          │             │               │                   └ False
          │             │               └ <nonebot_plugin_pixivbot_onebot_v11.protocol_dep.post_dest.PostDestination object at 0xffff82f2eb00>
          │             └ ('R18',)
          └ functools.partial(<bound method PermissionInterceptor.intercept of <nonebot_plugin_pixivbot.handler.interceptor.permission_in...
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_pixivbot/handler/interceptor/permission_interceptor.py", line 34, in intercept
    await wrapped_func(*args, post_dest=post_dest, silently=silently, **kwargs)
          │             │               │                   │           └ {'count': 1}
          │             │               │                   └ False
          │             │               └ <nonebot_plugin_pixivbot_onebot_v11.protocol_dep.post_dest.PostDestination object at 0xffff82f2eb00>
          │             └ ('R18',)
          └ functools.partial(<bound method PermissionInterceptor.intercept of <nonebot_plugin_pixivbot.handler.interceptor.cooldown_inte...
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_pixivbot/handler/interceptor/permission_interceptor.py", line 34, in intercept
    await wrapped_func(*args, post_dest=post_dest, silently=silently, **kwargs)
          │             │               │                   │           └ {'count': 1}
          │             │               │                   └ False
          │             │               └ <nonebot_plugin_pixivbot_onebot_v11.protocol_dep.post_dest.PostDestination object at 0xffff82f2eb00>
          │             └ ('R18',)
          └ functools.partial(<bound method TimeoutInterceptor.intercept of <nonebot_plugin_pixivbot.handler.interceptor.timeout_intercep...
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_pixivbot/handler/interceptor/timeout_interceptor.py", line 21, in intercept
    await wait_for(wrapped_func(*args, post_dest=post_dest, silently=silently, **kwargs),
          │        │             │               │                   │           └ {'count': 1}
          │        │             │               │                   └ False
          │        │             │               └ <nonebot_plugin_pixivbot_onebot_v11.protocol_dep.post_dest.PostDestination object at 0xffff82f2eb00>
          │        │             └ ('R18',)
          │        └ functools.partial(<bound method LoadingPromptInterceptor.intercept of <nonebot_plugin_pixivbot.handler.interceptor.loading_pr...
          └ <function wait_for at 0xffffa3c535b0>
  File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
           │   └ <method 'result' of '_asyncio.Task' objects>
           └ <Task finished name='Task-624342' coro=<LoadingPromptInterceptor.intercept() done, defined at /usr/local/lib/python3.10/dist-...
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_pixivbot/handler/interceptor/loading_prompt_interceptor.py", line 33, in intercept
    await wrapped_func(*args, post_dest=post_dest, silently=silently, **kwargs)
          │             │               │                   │           └ {'count': 1}
          │             │               │                   └ False
          │             │               └ <nonebot_plugin_pixivbot_onebot_v11.protocol_dep.post_dest.PostDestination object at 0xffff82f2eb00>
          │             └ ('R18',)
          └ functools.partial(<bound method RecordReqInterceptor.intercept of <nonebot_plugin_pixivbot.handler.interceptor.record_req_int...
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_pixivbot/handler/interceptor/record_req_interceptor.py", line 20, in intercept
    await wrapped_func(*args, post_dest=post_dest, silently=silently, **kwargs)
          │             │               │                   │           └ {'count': 1}
          │             │               │                   └ False
          │             │               └ <nonebot_plugin_pixivbot_onebot_v11.protocol_dep.post_dest.PostDestination object at 0xffff82f2eb00>
          │             └ ('R18',)
          └ functools.partial(<bound method PermissionInterceptor.intercept of <nonebot_plugin_pixivbot.handler.interceptor.service_inter...
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_pixivbot/handler/interceptor/permission_interceptor.py", line 34, in intercept
    await wrapped_func(*args, post_dest=post_dest, silently=silently, **kwargs)
          │             │               │                   │           └ {'count': 1}
          │             │               │                   └ False
          │             │               └ <nonebot_plugin_pixivbot_onebot_v11.protocol_dep.post_dest.PostDestination object at 0xffff82f2eb00>
          │             └ ('R18',)
          └ <bound method Handler._parse_args_and_actual_handle of <nonebot_plugin_pixivbot.handler.common.random_illust.RandomIllustHand...
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_pixivbot/handler/base.py", line 130, in _parse_args_and_actual_handle
    await self.actual_handle(post_dest=post_dest, silently=silently, **kwargs)
          │    │                       │                   │           └ {'count': 1, 'word': 'R18'}
          │    │                       │                   └ False
          │    │                       └ <nonebot_plugin_pixivbot_onebot_v11.protocol_dep.post_dest.PostDestination object at 0xffff82f2eb00>
          │    └ <function RandomIllustHandler.actual_handle at 0xffff94f6a290>
          └ <nonebot_plugin_pixivbot.handler.common.random_illust.RandomIllustHandler object at 0xffff94f7ca00>
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_pixivbot/handler/common/random_illust.py", line 57, in actual_handle
    await self.post_illusts(illusts,
          │    │            └ [Illust(id=104513549, title='【1/29新刊①サンプル】『タダでは起きない！』', type='manga', image_urls=ImageUrls(square_medium='https://i.pximg.net...
          │    └ <function Handler.post_illusts at 0xffffa23abe20>
          └ <nonebot_plugin_pixivbot.handler.common.random_illust.RandomIllustHandler object at 0xffff94f7ca00>
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_pixivbot/handler/base.py", line 65, in post_illusts
    await self.post_illust(illusts[0], header=header, number=number, post_dest=post_dest)
          │    │           │                  │              │                 └ <nonebot_plugin_pixivbot_onebot_v11.protocol_dep.post_dest.PostDestination object at 0xffff82f2eb00>
          │    │           │                  │              └ None
          │    │           │                  └ '这是您点的R18图'
          │    │           └ [Illust(id=104513549, title='【1/29新刊①サンプル】『タダでは起きない！』', type='manga', image_urls=ImageUrls(square_medium='https://i.pximg.net...
          │    └ <function Handler.post_illust at 0xffffa23abd90>
          └ <nonebot_plugin_pixivbot.handler.common.random_illust.RandomIllustHandler object at 0xffff94f7ca00>
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_pixivbot/handler/base.py", line 55, in post_illust
    await self.postman_manager.send_illusts(model, post_dest=post_dest)
          │    │                            │                └ <nonebot_plugin_pixivbot_onebot_v11.protocol_dep.post_dest.PostDestination object at 0xffff82f2eb00>
          │    │                            └ IllustMessagesModel(header='这是您点的R18图', messages=[IllustMessageModel(id=104513549, title='【1/29新刊①サンプル】『タダでは起きない！』', author='...
          │    └ <nonebot_plugin_pixivbot.context.Inject object at 0xffffa23a1600>
          └ <nonebot_plugin_pixivbot.handler.common.random_illust.RandomIllustHandler object at 0xffff94f7ca00>
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_pixivbot/handler/recorder.py", line 101, in send_illusts
    await self.delegation.send_illusts(model, post_dest=post_dest)
          │    │          │            │                └ <nonebot_plugin_pixivbot_onebot_v11.protocol_dep.post_dest.PostDestination object at 0xffff82f2eb00>
          │    │          │            └ IllustMessagesModel(header='这是您点的R18图', messages=[IllustMessageModel(id=104513549, title='【1/29新刊①サンプル】『タダでは起きない！』', author='...
          │    │          └ <function PostmanManager.send_illusts at 0xffffa23aac20>
          │    └ <nonebot_plugin_pixivbot.protocol_dep.postman.PostmanManager object at 0xffff94f614e0>
          └ <nonebot_plugin_pixivbot.handler.recorder.RecordPostmanManager object at 0xffff79daf4c0>
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_pixivbot/protocol_dep/postman.py", line 40, in send_illusts
    return await self[post_dest.adapter].send_illusts(model, post_dest=post_dest)
                 │    │         │                     │                └ <nonebot_plugin_pixivbot_onebot_v11.protocol_dep.post_dest.PostDestination object at 0xffff82f2eb00>
                 │    │         │                     └ IllustMessagesModel(header='这是您点的R18图', messages=[IllustMessageModel(id=104513549, title='【1/29新刊①サンプル】『タダでは起きない！』', author='...
                 │    │         └ <property object at 0xffff9f895da0>
                 │    └ <nonebot_plugin_pixivbot_onebot_v11.protocol_dep.post_dest.PostDestination object at 0xffff82f2eb00>
                 └ <nonebot_plugin_pixivbot.protocol_dep.postman.PostmanManager object at 0xffff94f614e0>
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_pixivbot_onebot_v11/protocol_dep/postman.py", line 84, in send_illusts
    await post_dest.post(messages)
          │         │    └ [[MessageSegment(type='text', data={'text': '这是您点的R18图'})], [MessageSegment(type='image', data={'file': 'base64://iVBORw0KGgo...
          │         └ <function PostDestination.post at 0xffff94f97ac0>
          └ <nonebot_plugin_pixivbot_onebot_v11.protocol_dep.post_dest.PostDestination object at 0xffff82f2eb00>
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_pixivbot_onebot_v11/protocol_dep/post_dest.py", line 49, in post
    await self.post_multiple(message)
          │    │             └ [[MessageSegment(type='text', data={'text': '这是您点的R18图'})], [MessageSegment(type='image', data={'file': 'base64://iVBORw0KGgo...
          │    └ <function PostDestination.post_multiple at 0xffff94f97be0>
          └ <nonebot_plugin_pixivbot_onebot_v11.protocol_dep.post_dest.PostDestination object at 0xffff82f2eb00>
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_pixivbot_onebot_v11/protocol_dep/post_dest.py", line 94, in post_multiple
    await self.bot.send_group_forward_msg(
          │    └ <property object at 0xffff9f8663e0>
          └ <nonebot_plugin_pixivbot_onebot_v11.protocol_dep.post_dest.PostDestination object at 0xffff82f2eb00>
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/adapter/bot.py", line 120, in call_api
    raise exception
          └ ActionFailed(data=None, echo='46', msg='EMPTY_NODES', retcode=100, status='failed', wording='未找到任何可发送的合并转发信息')
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/adapter/bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
                   │    │       │         │     │      └ {'group_id': 497560431, 'messages': [{'type': 'node', 'data': {'name': 'ρД∂\u200b', 'uin': '2858036838', 'content': [MessageS...
                   │    │       │         │     └ 'send_group_forward_msg'
                   │    │       │         └ Bot(type='OneBot V11', self_id='2858036838')
                   │    │       └ <function Adapter._call_api at 0xffffa2ee5750>
                   │    └ Adapter(name='OneBot V11')
                   └ Bot(type='OneBot V11', self_id='2858036838')
  File "/usr/local/lib/python3.10/dist-packages/nonebot/adapters/onebot/v11/adapter.py", line 132, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
           │                       │    │             │     │    └ 30.0
           │                       │    │             │     └ 46
           │                       │    │             └ <function ResultStore.fetch at 0xffffa2ee5240>
           │                       │    └ <nonebot.adapters.onebot.store.ResultStore object at 0xffffa2ed9720>
           │                       └ Adapter(name='OneBot V11')
           └ <function handle_api_result at 0xffffa304e9e0>
  File "/usr/local/lib/python3.10/dist-packages/nonebot/adapters/onebot/v11/utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
          │              └ {'data': None, 'echo': '46', 'msg': 'EMPTY_NODES', 'retcode': 100, 'status': 'failed', 'wording': '未找到任何可发送的合并转发信息'}
          └ <class 'nonebot.adapters.onebot.v11.exception.ActionFailed'>

nonebot.adapters.onebot.v11.exception.ActionFailed

**Comment by ssttkkl** [comment]
看起来是发送群聊合并消息的时候报错，但是我这边没有办法复现
你的go-cqhttp是最新版本的吗（1.0.0rc4）

**Comment by Kimaru-bili** [comment]
是的，用的nonebot-gocqhttp那个插件

**Comment by ssttkkl** [comment]
1.7.1版本增加了pixiv_onebot_send_forward_message配置项，用于配置是通过合并转发消息发送还是发送多条消息
设置为never时发送多条消息，尝试一下能否解决
