### ISSUE TITLE
[WinError 1225] 远程计算机拒绝网络连接

### ISSUE THREAD

**Issue by rickly233** [ssttkkl/nonebot-plugin-pixivbot#129]
配置了代理过后便报了这个错
![image](https://user-images.githubusercontent.com/92252768/215120379-5d3f0055-9094-4bf7-93db-912887731cf1.png)
![image](https://user-images.githubusercontent.com/92252768/215120443-3d204f62-2475-438c-95e7-1723b41775cf.png)
下面是.env.prod配置图
![image](https://user-images.githubusercontent.com/92252768/215120971-96b6c962-513c-4438-8457-d93a0763488c.png)

**Comment by ssttkkl** [comment]
配置没问题，大概是你的代理问题，你确定代理是socks5协议的吗
