### ISSUE TITLE
使用提示内部错误

### ISSUE THREAD

**Issue by longlongago7** [ssttkkl/nonebot-plugin-pixivbot#136]
小白提问：按照文档所给的方法获取了refresh_token并且写入了.env.prod文件里面，但还是有这种报错，求问该如何解决
![2~} ~LA$%CY@_ ~ {XERQ(2](https://user-images.githubusercontent.com/102451445/220123854-9caa704f-c295-4f5c-b357-680b1d03a6d2.png)

**Comment by ssttkkl** [comment]
看看日志
________________________________
From: longlongago7 ***@***.***>
Sent: Monday, February 20, 2023 9:42:43 PM
To: ssttkkl/nonebot-plugin-pixivbot ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ssttkkl/nonebot-plugin-pixivbot] 使用提示内部错误 (Issue #136)


小白提问：按照文档所给的方法获取了refresh_token并且写入了.env.prod文件里面，但还是有这种报错，求问该如何解决
[2~} ~LA$%CY@_ ~ {XERQ(2]<https://user-images.githubusercontent.com/102451445/220123854-9caa704f-c295-4f5c-b357-680b1d03a6d2.png>

―

**Comment by ssttkkl** [comment]
pip install nonebot-plugin-pixivbot --force-reinstall
执行上面的命令重新安装试试
________________________________

**Comment by longlongago7** [comment]
这个是控制台给的信息，日志我看着logs文件夹的貌似是gocq的日志
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: noneb
ot_plugin_access_control_permission
[SQL: SELECT nonebot_plugin_access_control_permission.subject, nonebot_plugin_ac
cess_control_permission.service, nonebot_plugin_access_control_permission.allow

FROM nonebot_plugin_access_control_permission
WHERE nonebot_plugin_access_control_permission.service = ? AND nonebot_plugin_ac
cess_control_permission.subject = ?]
[parameters: ('nonebot_plugin_pixivbot.common.ranking', 'onebot:2668779158')]

**Comment by ssttkkl** [comment]
上游插件nonebot-plugin-access-control的问题，执行`pip install nonebot-plugin-access-control==0.3.6`安装新版本即可

**Comment by longlongago7** [comment]
> 
现在控制台报错这个：
pixivpy_async.error.NoTokenError: No access_token Found!
![image](https://user-images.githubusercontent.com/102451445/220267068-88fa942c-64b7-47ea-8ac6-a414d5d26d67.png)

刚刚执行pip install nonebot-plugin-access-control==0.3.6这个命令的时候貌似也有点报错
![image](https://user-images.githubusercontent.com/102451445/220267009-7ef51b62-0218-4772-81ae-8d0b2ddcb5c0.png)

**Comment by ssttkkl** [comment]
这个就单纯是没能登录成功，检查网络和代理有无问题
________________________________

**Comment by longlongago7** [comment]
意思是挂梯子吗，还是重新获取refresh_token，刚刚尝试着挂了梯子也是这个报错（确认浏览器能上pixiv）

**Comment by ssttkkl** [comment]
代理是在.env.prod文件里配置的吗，系统全局代理不一定有用
________________________________

**Comment by longlongago7** [comment]
不太明白，.env.prod文件里应该是这样子吗？
![image](https://user-images.githubusercontent.com/102451445/220386004-40eacba2-431b-4006-98fc-2c18289ea9c8.png)
梯子我是这样的
![image](https://user-images.githubusercontent.com/102451445/220386490-fc7471b8-6274-4260-a93c-26bd6ebf2058.png)

**Comment by longlongago7** [comment]
不太明白，.env.prod文件里应该是这样子的吗
![image](https://user-images.githubusercontent.com/102451445/220386850-247ae94f-e043-4c1d-ba53-eb9f9b5f52a6.png)
我的梯子是这样使用的
![image](https://user-images.githubusercontent.com/102451445/220387016-8d8667d4-fd02-4b7a-9d0c-28d7192ef6b7.png)

**Comment by ssttkkl** [comment]
pixiv_proxy=你的代理地址

这个因人而异，最好看看自己的梯子客户端设置的是什么

比如本地7890端口的HTTP代理就设置成pixiv_proxy=http://127.0.0.1:7890

**Comment by longlongago7** [comment]
就是在.env.prod里面加上pixiv_proxy=代理地址这条是嘛，咱这么加上了就成功了。感谢大佬耐心解答！
