### ISSUE TITLE
希望可以增加uid搜索和看看AI榜

### ISSUE THREAD

**Issue by Akisama514** [ssttkkl/nonebot-plugin-pixivbot#149]
希望增加功能：
1、因为部分画师名字输入比较麻烦，如果可以兼容uid搜索就好了；
2、最近ai榜质量挺好的，希望可以添加看看AI榜。

**Comment by ssttkkl** [comment]
按UID搜索其实是支持的，只是文档没写
AI榜我看看能不能支持
________________________________
From: Akisama514 ***@***.***>
Sent: Friday, March 10, 2023 12:07:42 AM
To: ssttkkl/nonebot-plugin-pixivbot ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ssttkkl/nonebot-plugin-pixivbot] 希望可以增加uid搜索和看看AI榜 (Issue #149)


希望增加功能：
1、因为部分画师名字输入比较麻烦，如果可以兼容uid搜索就好了；
2、最近ai榜质量挺好的，希望可以添加看看AI榜。

―

**Comment by Akisama514** [comment]
好的感谢大佬，下午的时候试了下uid搜索没成功，还以为不可以，可能那时网络问题，刚试了可以的

**Comment by ssttkkl** [comment]
v1.7.8已新增看看AI榜功能
