### ISSUE TITLE
订阅画师作品更新无法收到更新

### ISSUE THREAD

**Issue by TechOtakupoi233** [ssttkkl/nonebot-plugin-pixivbot#151]
如题，群内订阅了一些画师，但是从来没有收到过一次推送。
私聊的关注推送和群组的日榜定时推送都是正常工作的。
研究发现，pixivbot如果没有获取过此用户的图片，使用ID获取这个user总是返回user_id not found的错误。
以ATDAN-(6662895)为例:
![屏幕截图 2023-03-14 150825](https://user-images.githubusercontent.com/36725374/224928707-f4233798-d8e9-4b62-8185-e3329ebe5f83.png)
但是以ID搜图可以工作:
![屏幕截图 2023-03-14 151043](https://user-images.githubusercontent.com/36725374/224928739-727620ce-190a-4475-8db6-a09943c65b72.png)

此时再执行/pixivbot watch fetch，居然又可以了？
![屏幕截图 2023-03-14 151227](https://user-images.githubusercontent.com/36725374/224928862-7c2e7a7a-1b4a-4790-b171-f2fe4fde5bcf.png)

再换一个画师Pottsness(59336265)，群内无搜图历史也无订阅历史（但是有私聊关注者推送）
![image](https://user-images.githubusercontent.com/36725374/224924537-de97917a-2965-48fa-b8a8-d3dfc7c5448e.png)
（ErrorLog太长，screen不能滚屏）
![image](https://user-images.githubusercontent.com/36725374/224924210-fa0c4a5c-4955-4350-9b89-16e05c8b0122.png)
但是第一次使用名称搜图之后，基于ID的功能就都正常了:
![image](https://user-images.githubusercontent.com/36725374/224924967-231585d3-78a3-446e-be84-f0ec8338eabf.png)
![屏幕截图 2023-03-14 152256](https://user-images.githubusercontent.com/36725374/224929025-227cecf5-a53d-4a1d-998a-572cd70ebfb8.png)

总之就是这样，看样子跟数据库有点关系。（使用的是默认的SQLite）
另一个问题是，大群里群友一拥而上发图的时候经常会遇到Database Locked错误。

**Comment by ssttkkl** [comment]
1. 那个not found其实不是找不到画师的意思，是执行过程中意料之中的。功能我刚测过应该是能正常工作的
2. <class 'AttributeError'>'illust'这个bug我记得已经修了，更新最新版试试
3. SQLite遇到高并发是会Database Locked，如果可以的话建议使用PostgreSQL或者MongoDB作为数据库，今后也会考虑增加不使用本地缓存的选项解决这个问题

**Comment by ssttkkl** [comment]
如果画师更新推送确实有问题的话可以试一下这个暴力测试方法

1. 确保bot关闭，用DBeaver或者其他能打开SQLite数据库的软件打开bot目录下`pixiv_bot.db`
2. 在`watch_task`表里找到对应ID的任务，把checkpoint改成一个相对较早的时间点，写入之后重新启动bot
3. 执行watch fetch命令，此时应该会把投稿时间晚于刚刚改的checkpoint的作品全部发出来，并且会将这条记录checkpoint更新为现在的时间

**Comment by ssttkkl** [comment]
> 看起来是用了过时的版本(1.7.4)，更新到1.7.7之后<class 'AttributeError'>'illust'看起来确实修复了（ 但是推送好像还是一样的，甚至几个小时前才获取过的Dan老师的id也又出意外了... ![image](https://user-images.githubusercontent.com/36725374/224984572-7307a120-ff49-49cb-99c6-7071c3cd82f4.png)

推送看起来没问题，watch推送是更新推送，只有两次检查时间之间画师投稿了才会发送
以及你指令错了

**Comment by TechOtakupoi233** [comment]
我尝试了使用DBeaver编辑数据，但是遇到了数据库只读...软件的切换只读模式按钮也没有效果。
[SQLITE_READONLY] Attempt to write a readonly database (attempt to write a readonly database)
直接把整个db拖进窗口的话，就直接OutOfMemory了。

**Comment by TechOtakupoi233** [comment]
像这样尝试修改了群组内画师推送的时间和私聊的关注推送时间。
![image](https://user-images.githubusercontent.com/36725374/225047227-ec4cf328-aac4-4fc2-a729-03ccca773456.png)
![image](https://user-images.githubusercontent.com/36725374/225047792-209c21e6-6c5f-4ec6-b0f2-65fe529f1567.png)
结果是，群组依然没有收到一张图，（DAN老师从三月开始到现在发了两张图，而且都有私聊推送过）但是私聊图全部到账了。
![image](https://user-images.githubusercontent.com/36725374/225049080-c7536f16-b715-457b-b3d1-5412108846a3.png)

**Comment by ssttkkl** [comment]
可以的话把配置文件也发上来看看

**Comment by TechOtakupoi233** [comment]
感谢，清除缓存后，图到账了！

不过还有一个问题，启动Log中有提到这两个配置选项Deprecated，请问作为替代的功能有文档吗？
pixiv_query_cooldown=
pixiv_no_query_cooldown_users=

**Comment by TechOtakupoi233** [comment]
噢，是指通过nonebot-plugin-access-control的限流功能来实现对service服务调用的频率限制吧？
我之前脑子没转过来（

**Comment by ssttkkl** [comment]
v1.7.8已修复订阅画师更新无效的问题
