### ISSUE TITLE
TypeError: Can't instantiate abstract class PostDestination with abstract method bot

### ISSUE THREAD

**Issue by simpleYOTO** [ssttkkl/nonebot-plugin-pixivbot#153]
![1678847178644](https://user-images.githubusercontent.com/107185219/225189040-9a886a67-59b9-40cf-bcf8-3bb22d8899da.jpg)
请教大佬这是什么原因
配置我就配置了refresh_tokne和代理
pixiv_refresh_token="xxxxx"
pixiv_proxy="http://127.0.0.1:xxx"
我也想顺便问一下这样子格式对了
万分感谢！

**Comment by ssttkkl** [comment]
升级最新版试试

**Comment by simpleYOTO** [comment]
哦哦哦，可以了，感谢！
