### ISSUE TITLE
功能请求：消息被服务器拒绝时进行提示

### ISSUE THREAD

**Issue by TechOtakupoi233** [ssttkkl/nonebot-plugin-pixivbot#155]
就像自主规制一样，把图片替换成提示，附上图片信息，只是把自主规制的提示换成被服务器拦截？（

**Comment by TechOtakupoi233** [comment]
就是诸如“发送转发消息失败，可能账号被风控”之类的，消息被服务器拒绝（被tx拦截了）的情况，总之就是消息因为服务器方面的原因发送失败，对这类状况进行一个回报，经常有群友等图等半天等不到一看后台：被截了。

**Comment by ssttkkl** [comment]
已于版本1.8.3添加此功能：
图片发送失败时，回复“图片发送失败，可能是机器人被风控”
