### ISSUE TITLE
只对某个群聊报错

### ISSUE THREAD

**Issue by Fhm-newbie** [ssttkkl/nonebot-plugin-pixivbot#163]
![图片](https://user-images.githubusercontent.com/63446200/227864426-bf2d229a-70d9-453f-97b6-e54aa421793a.png)
大佬您好，我这边出现了点问题。。。我在其他群使用pixivbot的指令都没有问题，只在某个特定的群里面使用 来张图 指令时日志会出现以上报错，该群唯一的不同之处可能在于这个新建的bot在使用过一次指令前前我先用ac limit对这个群聊的pixivbot使用次数进行了限制。

另外，如果我在该群使用pixivbot help指令的话，会提示：
内部错误：<class 'sqlalchemy.exc.MissingGreenlet'>greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)。
这点同样是只有在该群会出现的错误。

最后就是，我想尝试清理一下缓存，于是使用了invaildate_cache。但是又会显示：
内部错误：<class 'TypeError'>object bool can't be used in 'await' expression

如果大佬有空的话能麻烦大佬指点一下吗？非常感谢

**Comment by ssttkkl** [comment]
你再往上翻翻把报错日志截全了，如果太长了可以保存到txt发出来
我这边除了清缓存以外的问题都没复现
最后你要不要先试试pip install nonebot-plugin-pixivbot==1.8.0 --force-reinstall

**Comment by Fhm-newbie** [comment]
不好意思大佬，因为您一天没回我我之前已经重装系统。。。
但是我尝试了一下复现，方法就是，给一个群的同一个对象设置两个ac limit add，不过这样的话我就在怀疑是不是 access_control那个插件的问题。。。

**Comment by Fhm-newbie** [comment]
![Screenshot_20230329_151922_com tencent mobileqq_edit_1047843114963027](https://user-images.githubusercontent.com/63446200/228456752-7d7b45f4-8875-419e-b067-2497e684256c.jpg)
大概像这样，就会出那个报错
