### ISSUE TITLE
可以适配云崽魔改的py插件吗

### ISSUE THREAD

**Issue by lintonxue00** [ssttkkl/nonebot-plugin-pixivbot#165]
schedle random_illust 01:00*x ロリ                                   [PyBot][08:36:50.480][INFO] [message] 触发 Matcher(type='message', module=nonebot_plugin_pixivbot.handler.command.command)                    [PyBot][08:36:50.497][ERROR] [message]Running Matcher(type='message', module=nonebot_plugin_pixivbot.handler.command.command) failed.         Traceback (most recent call last):                                       File "/root/.cache/pypoetry/virtualenvs/py-plugin-8_cve6GP-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 141, in _check_matcher                                                                          await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)                                                                   > File "/root/.cache/pypoetry/virtualenvs/py-plugin-8_cve6GP-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 187, in _run_matcher     await matcher.run(bot, event, state, stack, dependency_cache)        File "/root/.cache/pypoetry/virtualenvs/py-plugin-8_cve6GP-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 753, in run                                                                    await self.simple_run(bot, event, state, stack, dependency_cache)    File "/root/.cache/pypoetry/virtualenvs/py-plugin-8_cve6GP-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 728, in simple_run                                                             await handler(                                                       File "/root/.cache/pypoetry/virtualenvs/py-plugin-8_cve6GP-py3.9/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 104, in __call__                                                                  values = await self.solve(**kwargs)                                  File "/root/.cache/pypoetry/virtualenvs/py-plugin-8_cve6GP-py3.9/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 219, in solve                                                                     values = await asyncio.gather(                                       File "/root/.cache/pypoetry/virtualenvs/py-plugin-8_cve6GP-py3.9/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 208, in _solve_field                                                              value = await cast(Param, field.field_info)._solve(**params)         File "/root/.cache/pypoetry/virtualenvs/py-plugin-8_cve6GP-py3.9/lib/python3.9/site-packages/nonebot/internal/params.py", line 162, in _solve                                                                          return await task                                                    File "/root/.cache/pypoetry/virtualenvs/py-plugin-8_cve6GP-py3.9/lib/python3.9/site-packages/nonebot/utils.py", line 114, in _wrapper           result = await loop.run_in_executor(None, pfunc)                     File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run                                                                   result = self.fn(*self.args, **self.kwargs)                          File "/root/.cache/pypoetry/virtualenvs/py-plugin-8_cve6GP-py3.9/lib/python3.9/site-packages/nonebot_plugin_pixivbot/protocol_dep/post_dest.py", line 80, in post_destination                                          return context.require(PostDestinationFactoryManager).from_event(bot, event)                                                                File "/root/.cache/pypoetry/virtualenvs/py-plugin-8_cve6GP-py3.9/lib/python3.9/site-packages/nonebot_plugin_pixivbot/protocol_dep/post_dest.py", line 76, in from_event                                                return self[get_adapter_name(bot)].from_event(bot, event)            File "/root/.cache/pypoetry/virtualenvs/py-plugin-8_cve6GP-py3.9/lib/python3.9/site-packages/nonebot_plugin_pixivbot/protocol_dep/protocol_dep.py", line 33, in __getitem__                                            return self.require(adapter)                                         File "/root/.cache/pypoetry/virtualenvs/py-plugin-8_cve6GP-py3.9/lib/python3.9/site-packages/nonebot_plugin_pixivbot/protocol_dep/protocol_dep.py", line 29, in require                                                raise RuntimeError(f"暂不支持{adapter}")                           RuntimeError: 暂不支持oneadapter

**Comment by lintonxue00** [comment]
这是地址https://gitee.com/realhuhu/py-plugin

**Comment by ssttkkl** [comment]
不考虑适配不在官方上架的适配器
