### ISSUE TITLE
地址错误？

### ISSUE THREAD

**Issue by lovecpm** [ssttkkl/nonebot-plugin-pixivbot#68]
内部错误：<class 'aiohttp.client_exceptions.ClientConnectorError'>Cannot connect to host none:443 ssl:default [getaddrinfo failed]
如果加了http代理，在代理日志也提示accept //none:443 [proxy]

**Comment by ssttkkl** [comment]
我这边没有这个问题，或许是你的配置文件格式不正确

**Comment by yangdffdzvzvr** [comment]
内部错误：<class 'pixivpy_async.error.NoTokenError'>No access_token Found!
我填了也不管用。。。
