### ISSUE TITLE
求解是因为哪部分的配置出错出现的问题

### ISSUE THREAD

**Issue by Ctumille** [ssttkkl/nonebot-plugin-pixivbot#77]
特地给这个插件单独开了个部分，仍然无法启动，求解是哪个部分的配置出现了问题。
错误部分：
![error](https://user-images.githubusercontent.com/7392476/198675959-d1d285e6-5be6-4285-8ea5-9e1eb8c0bfa5.png)
.env.prod部分：
![envprod](https://user-images.githubusercontent.com/7392476/198676040-bb0ff982-997b-4ba2-8bd1-ec75892268a5.png)

**Comment by ssttkkl** [comment]
mongodb需要4.2以上的版本

**Comment by Ctumille** [comment]
> mongodb需要4.2以上的版本

谢谢，问题解决了，没想到解决方法这么简单
