### ISSUE TITLE
请问有没有办法只发送pid不发送地址

### ISSUE THREAD

**Issue by Ctumille** [ssttkkl/nonebot-plugin-pixivbot#96]
虽然确实听起来很傻但是因为QQ让p站红了导致发链接看的很心慌，也不知道QQ有没有什么检测机制

**Comment by ssttkkl** [comment]
https://github.com/ssttkkl/nonebot-plugin-pixivbot-onebot-v11/blob/19eee9e45b6615e766b9991e45b523bd145e09ca/src/nonebot_plugin_pixivbot_onebot_v11/protocol_dep/postman.py#L38

可以拉到本地修改这里的代码然后自己打包一份再安装

**Comment by Ctumille** [comment]
> https://github.com/ssttkkl/nonebot-plugin-pixivbot-onebot-v11/blob/19eee9e45b6615e766b9991e45b523bd145e09ca/src/nonebot_plugin_pixivbot_onebot_v11/protocol_dep/postman.py#L38
> 
> 可以拉到本地修改这里的代码然后自己打包一份再安装

那还是算了，将来再更新您的代码时还得再改一次，让大家别盯着警告看了（

**Comment by ssttkkl** [comment]
#98 因为带了P站链接导致私聊消息发不出去

**Comment by ssttkkl** [comment]
已修复，请更新nonebot-plugin-pixivbot-onebot-v11到1.5.1版本
