### ISSUE TITLE
内部错误：<class 'pixivpy_async.error.NoTokenError'>No access_token Found!

### ISSUE THREAD

**Issue by yangdffdzvzvr** [ssttkkl/nonebot-plugin-pixivbot#97]
内部错误：<class 'pixivpy_async.error.NoTokenError'>No access_token Found!
![Y21R~I$ 8DR6J1R3K{ O`W](https://user-images.githubusercontent.com/118903437/203549474-c5c399cc-5b17-4e52-a6f4-64956c4465d6.png)

**Comment by lovecpm** [comment]
看看配置文件是什么样的？

**Comment by yangdffdzvzvr** [comment]
最小配置

**Comment by yangdffdzvzvr** [comment]
![G D{%D01AV %P J07OP2LT](https://user-images.githubusercontent.com/118903437/203551398-6f4886bc-90e8-4a37-9af5-675e970220e9.png)

**Comment by yangdffdzvzvr** [comment]
> 看看配置文件是什么样的？

最小配置，只填了token

**Comment by yangdffdzvzvr** [comment]
> 看看.env文件，里面是不是environment=dev 顺便把nonebot启动输出贴上来，看看配置项成功读取了没有

![SOX~CIT(NG)S`5O2GG}U923](https://user-images.githubusercontent.com/118903437/203590270-ce558341-6e4d-476d-9dcc-a28bc2b0dcdb.png)
![$E~XEZ06}IVC }B`9E(292F](https://user-images.githubusercontent.com/118903437/203590291-f51b4baa-23c7-44ce-9849-2a5a72d22063.png)

**Comment by yangdffdzvzvr** [comment]
![$E~XEZ06}IVC }B`9E(292F](https://user-images.githubusercontent.com/118903437/203590570-24a8ccf3-1340-4f04-902d-50242d76b8c8.png)

**Comment by yangdffdzvzvr** [comment]
![SOX~CIT(NG)S`5O2GG}U923](https://user-images.githubusercontent.com/118903437/203590645-b0579a9e-b259-48ba-bac0-06f4779f68f7.png)

**Comment by yangdffdzvzvr** [comment]
> 看看.env文件，里面是不是environment=dev 顺便把nonebot启动输出贴上来，看看配置项成功读取了没有

是没添加代理吗？

**Comment by yangdffdzvzvr** [comment]
![KKC)KKMR4D(890P$FC@KR(8](https://user-images.githubusercontent.com/118903437/203592116-ad11a935-3dad-428a-9483-b08ecd91d2db.png)

**Comment by ssttkkl** [comment]
是，国内没代理就没法访问p站获取access_token
________________________________

**Comment by Cutlars** [comment]
我昨天晚上配置的时候也遇到同样问题，我想问下pixiv_proxy的格式是什么。proxy格式当时填的是:127.0.0.1:xxxxx，我尝试将获取fresh_token和access_token的接口直接接入bapi.py这个文件从而拿到数据，然后运行的时候报错，后来换成socks5:127.0.0.1:xxxxx,报错host为空，现在上班没法提供log

**Comment by lovecpm** [comment]
我是用http://的

**Comment by Cutlars** [comment]
通过以下方式并且配置proxy能连接到pixiv，但会弹出浏览器需要你手动点击登录
![企业微信截图_16692945082117](https://user-images.githubusercontent.com/71304393/203789993-0208710d-76eb-4467-b426-9bee9035b8f9.png)

**Comment by ssttkkl** [comment]
> Reference in new is

协议://地址:端口号

比如socks5就是socks5://127.0.0.1:xxxx

**Comment by yangdffdzvzvr** [comment]
我已经搞好了，就是使用中R18不能有效过滤，暂时不太敢用

**Comment by ssttkkl** [comment]
过滤R18最好的方式是把你账号的R18开关关掉（）
插件过滤实现的方式是过滤tag，遇到不好好标tag的画师就没辙了
