### ISSUE TITLE
QQ私聊无法发送图片

### ISSUE THREAD

**Issue by Cutlars** [ssttkkl/nonebot-plugin-pixivbot#98]
现在我能够成功运行，并且通过bot请求pixiv有返回，且数据库也成功入值，但是bot却发不出来消息，请问我需要从哪边开始排查
![fault2](https://user-images.githubusercontent.com/71304393/203790806-7b37b456-a9f1-4764-8375-f5f4ce0ec2fc.png)

**Comment by Cutlars** [comment]
![QQ图片20221124210527](https://user-images.githubusercontent.com/71304393/203791575-5d7b0649-0bff-43c1-95a8-1eea105b6423.png)

**Comment by Cutlars** [comment]
![fault3](https://user-images.githubusercontent.com/71304393/203793241-40d6735a-009e-48cd-a96c-c57596ec4775.png)

从这能看到bot已经发送了消息，但是并没有接收到

**Comment by Cutlars** [comment]
已解决，未知原因无法私聊发送，只能用于群

**Comment by ssttkkl** [comment]
我这边代码没更新过，20号之前私聊都好好的，20号开始私聊无法发送图片消息，怀疑是tx或者gocqhttp的问题

**Comment by ssttkkl** [comment]
经排查是消息带了P站链接所以无法发送，联系到前段时间开始腾讯把P站标成危险网站的缘故

**Comment by ssttkkl** [comment]
已修复，请更新nonebot-plugin-pixivbot-onebot-v11到1.5.1版本

**Comment by Cutlars** [comment]
> 已修复，请更新nonebot-plugin-pixivbot-onebot-v11到1.5.1版本

原来是这样，谢谢大佬排查
